/*TRIGGER EN LA BASE DE DATOS DE "REGISTRO_BOLETOS"*/
DROP TRIGGER IF EXISTS setTicketId;
DELIMITER //
CREATE TRIGGER setTicketId
AFTER INSERT ON registro_boletos.boletos
FOR EACH ROW BEGIN
	CALL vtigercrm600.setTickets(NEW.id);
END//
DELIMITER ;

DROP TRIGGER IF EXISTS setUpdateTicketId;
DELIMITER //
CREATE TRIGGER setUpdateTicketId
AFTER UPDATE ON registro_boletos.boletos
FOR EACH ROW BEGIN
	CALL vtigercrm600.setTickets(NEW.id);
END//
DELIMITER ;