DROP TRIGGER IF EXISTS bloqueo_spam;
DELIMITER | 
CREATE TRIGGER bloqueo_spam BEFORE INSERT ON ost_ticket
FOR EACH ROW BEGIN  
  IF NEW.ip_address LIKE CONCAT('188.143.232.','%') THEN
    SIGNAL SQLSTATE "45000" SET MESSAGE_TEXT = "IP BLOQUEADA";
  END IF;
END |
DELIMITER ;
